package com.vikson.projects.exceptions;

public enum ErrorCodes {

    NOT_CATEGORIZED(101),
    UNPRIVILEGED(102),
    PLAN_FOLDER_ALREADY_EXISTS(1),
    PLAN_ALREADY_EXISTS(2),
    PLAN_REVISION_ALREADY_EXISTS(3),
    PLAN_LIMIT_EXCEED(4),
    PROJECT_LIMIT_EXCEED(5),
    ENTITY_NOT_FOUND(6),
    USER_RESTRICTION_1(7),
    USER_RESTRICTION_2(8),
    INTERNAL_SERVER_ERROR(9),
    PRIVILEGE_REQUIRED(10),
    CREATE_PROJECT_FOLDER_PRIVILEGE(11),
    UPDATE_PROJECT_FOLDER_PRIVILEGE(12),
    CREATE_PROJECT_PRIVILEGE_1(13),
    CREATE_PROJECT_PRIVILEGE_2(14),
    MOVE_PROJECT_FOLDER_PRIVILEGE(15),
    NOT_A_PROJECT_MEMBER(16),
    BAD_TIMESTAMP_FORMAT(17),
    LOGO_SAVE(18),
    MAX_LOGO_SIZE(19),
    SAME_ORGANIZATION(20),
    PROJECT_WITH_NAME_ALREADY_EXISTS(21),
    MOVE_FOLDER_TO_ITSELF(22),
    MOVE_FOLDER_TO_CHILD(23),
    AVATAR_FILE_TYPE(24),
    FOLDER_UPDATE_OUTSIDE_ORGANIZATION(25),
    MOVE_FOLDER_TO_CHILD_OR_ITSELF(26),
    PROJECT_FOLDER_DELETE_WITH_CHILD(27),
    MOVE_FOLDER_OUTSIDE_ORGANIZATION(28),
    MOVE_PROJECT_OUTSIDE_ORGANIZATION(29),
    DELETE_PROJECT_FOLDER_OUTSIDE_ORGANIZATION(30),
    PARENT_FOLDER_OUTSIDE_ROOT(31),
    PARENT_FOLDER_OUTSIDE_ORGANIZATION(32),
    CREATE_PLAN_FOLDER_IN_UNKNOWN_PROJECT(33),
    PLAN_FOLDER_DELETE_WITH_CHILD(34),
    PLAN_TREE_FOR_UNKNOWN_PROJECT(35),
    CREATE_PLAN_IN_UNKNOWN_PROJECT(36),
    CREATE_PLAN_REVISION_NULL(37),
    CREATE_PLAN_PLANTYPE_NULL(38),
    CREATE_PLAN_PLANMETADATA_NULL(39),
    CURRENT_REVISION_CHANGE(40),
    ERROR_LOAD_PARENT_FOLDER(41),
    ERROR_CHOOSE_PARENT_FOLDER(42),
    WIDTH_NOT_SPECIFIED(43),
    HEIGHT_NOT_SPECIFIED(44),
    NE_LATLONG_NOT_SPECIFIED(45),
    SE_LATLONG_NOT_SPECIFIED(46),
    INVALID_NE_LATLONG(47),
    INVALID_SE_LATLONG(48),
    ARCHIVE_SIZE_NOT_SPECIFIED(49),
    EMPTY_PLAN_LEVEL(50),
    PLAN_LEVEL_NULL(51),
    MOVE_PLAN_PROJECT_ID_NULL(52),
    ERROR_LOAD_PARENT_PLAN_FOLDER(53),
    MOVE_PLAN_OUTSIDE_PROJECT(54),
    MOVE_PLAN_FOLDER_TO_ITSELF(55),
    MOVE_PLAN_FOLDER_TO_CHILD(56),
    PLAN_REVISION_IN_PROCESS(57),
    PLAN_REVISION_DIFFERENT_SIZE(58),
    INVALID_DTO(59),
    NOT_PARSABLE_TIMESTAMP(60),
    BIMPLUS_ALREADY_LINKED(61),
    BIMPLUS_REVISION_NOT_INT(62),
    BIMPLUS_PROJECT_NAME_REQUIRED(63),
    BIMPLUS_ATTACHMENT_NAME_REQUIRED(64),
    BIMPLUS_ATTACHMENT_ID_UPDATE_NOT_ALLOWED(65),
    BIMPLUS_RESOURCE_CHANGE_STATE(66);

    private final int code;

    ErrorCodes(int code) {
        this.code = code;
    }

    public int getCode() {
        return this.code;
    }
}
